language: c
dist: xenial
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
  - PINS="bitstring:. ppx_bitstring:."
  - PACKAGE=ppx_bitstring
  jobs:
  - OCAML_VERSION=4.04 TESTS=false
  - OCAML_VERSION=4.05 TESTS=false
  - OCAML_VERSION=4.06 TESTS=false
  - OCAML_VERSION=4.07 TESTS=false
  - OCAML_VERSION=4.08
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.10
  - OCAML_VERSION=4.11
os:
  - linux
jobs:
  include:
    - env: OCAML_VERSION=4.11
      os: osx
    - env: OCAML_VERSION=4.11
      os: freebsd
    - env: OCAML_VERSION=4.11
      arch: arm64
